api/__init__.py
from api_dice_roll import *

app.py
from flask import Flask, render_template, session
import controllers
import config
import api

# set url_prefix
prefix = ""

# Initialize Flask app with the template folder address
app = Flask(__name__, template_folder='templates')

# secret key - change / set if sessions are implemented
# app.secret_key = 'N5\\A\xa7!\x80\xa0j\xd1\xdf\x19\xc8n\n\x1e)(\xb1Z\x7f?\x07A'

# Register the controllers
app.register_blueprint(controllers.main, url_prefix=prefix)
app.register_blueprint(controllers.dice, url_prefix=prefix)
app.register_blueprint(api.api_dice_roll, url_prefix=prefix)
app.register_blueprint(controllers.resume, url_prefix=prefix)

# Listen on external IPs
# Set host and port information in config.py file
if __name__ == '__main__':
    # listen on external IPs
    app.run(host=config.env['host'], port=config.env['port'], debug=True)

controllers/__init__.py
from main import *
from dice import *
from resume import *

controllers/dice.py
from flask import *

dice = Blueprint('dice', __name__, template_folder='templates')

@dice.route('/dice')
def dice_route():
    options = {}

    return render_template("dice.html", **options)

controllers/main.py
from flask import *

main = Blueprint('main', __name__, template_folder='templates')

@main.route('/')
def main_route():
    options = {}

    return render_template("index.html", **options)

controllers/resume.py
from flask import *

resume = Blueprint('resume', __name__, template_folder='templates')

@resume.route('/resume')
def resume_route():
    options = {}

    return render_template("resume.html", **options)

templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
    <link rel="stylesheet" href="/static/css/style.css" />
    <link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <title>Joshua Agby</title>
</head>
<body>
    <!-- Navbar -->
    <div class="w3-top">
    <ul class="w3-navbar w3-blue w3-card-2 w3-left-align">
      <li class="w3-hide-medium w3-hide-large w3-opennav w3-right">
        <a class="w3-padding-large" href="javascript:void(0)" onclick="myFunction()" title="Toggle Navigation Menu"><i class="fa fa-bars"></i></a>
      </li>
      <li><a href="{{ url_for('main.main_route') }}" class="w3-hover-none w3-hover-text-grey w3-padding-large">HOME</a></li>
      <li class="w3-hide-small"><a href="http://www.joshagby.com" class="w3-padding-large">ABOUT ME</a></li>
      <li class="w3-hide-small"><a href="{{ url_for('resume.resume_route') }}" class="w3-padding-large">RESUME</a></li>
      <li class="w3-hide-small w3-dropdown-hover">
        <a href="javascript:void(0)" class="w3-hover-none w3-padding-large" title="More">PROJECTS<i class="fa fa-caret-down"></i></a>
        <div class="w3-dropdown-content w3-white w3-card-4">
          <a href="{{ url_for('dice.dice_route') }}">Dice Game</a>
        </div>
      </li>
      </ul>
    </div>

    <!-- Alternate Navbar for small screens -->
    <div id="navDemo" class="w3-hide w3-hide-large w3-hide-medium w3-top" style="margin-top:46px">
      <ul class="w3-navbar w3-left-align w3-black">
        <li><a class="w3-padding-large" href="TBD">TBD</a></li>
      </ul>
    </div>

    {% block content %}{% endblock %}

    <!-- Footer -->
    <footer class="w3-container w3-padding-32 w3-center w3-opacity w3-light-grey w3-large">
        <a href="https://www.facebook.com/josh.agby" target="_blank"><i class="fa fa-facebook-official w3-hover-text-indigo w3-xxlarge"></i></a>
        <a href="https://github.com/joshagby" target="_blank"><i class="fa fa-github w3-hover-text-indigo w3-xxlarge"></i></a>
        <a href="https://www.linkedin.com/in/joshua-agby-886550b2" target="_blank"><i class="fa fa-linkedin w3-hover-text-indigo w3-xxlarge"></i></a>
        <br><br><i class="w3-large">Last Updated: January 4, 2017</i>
    </footer>


  <script type="text/javascript" src="/static/js/main.js"></script>
</body>

</html>

templates/dice.html
{% extends "base.html" %}
{% block content %}
  <head>
    <link rel="stylesheet" href="/static/css/dice.css" />
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
    <script src="/static/js/dice.js"></script>
    <script src="/static/js/buildHTML.js"></script>
  </head>

  <div class="w3-container w3-content w3-padding-64" style="max-width:800px" id="dice">

    <div id="gameInfo">
      <p>Dice Game, created by Joshua Agby</p>
      <p>
        <b>Rules Overview:</b> <br>
        <table>
          <tr>
            <th>Objective</th>
            <td>Score more points than the computer. The game consists of three rounds. Your total score will be the sum of your points from each round.</td>
          </tr>
          <tr>
            <th>Round Rules</th>
            <td>Each round you may roll a single die as many times as you wish. Your score for that round will be the sum of all dice rolls after you decide to stop. If at any time you roll a <i>one</i>, your turn will end and you will receive no points for that round. This is called a <i>bust</i>.</td>
          </tr>
        </table>

        <br> Good Luck! <br>
      </p>
    </div>

    <p id="statusText"></p>

    <div id="diceDisplay"></div>

    <div id="playButtons">
      <form action="javascript:rollDice('1');" id="rollDiceForm">
        <button type="submit" id="rollDiceButton">Roll Dice</button>
      </form>
      <form action="javascript:endRound();" id="endRoundForm">
        <button type="submit" id="endRoundButton">End Turn</button>
      </form>
    </div>

    <br>

    <table id="scoreTable">
      <tr>
        <th>Round:</th>
        <th>Your Score:</th>
        <th>Opponent Score:</th>
      </tr>
      <tr>
        <th>One</th>
        <td id=r1p1>0</td>
        <td id=r1p2>0</td>
      </tr>
      <tr>
        <th>Two</th>
        <td id=r2p1>0</td>
        <td id=r2p2>0</td>
      </tr>
      <tr>
        <th>Three</th>
        <td id=r3p1>0</td>
        <td id=r3p2>0</td>
      </tr>
      <tr>
        <th>TOTAL</th>
        <th id=p1tot>0</th>
        <th id=p2tot>0</th>
      </tr>
    </table>
    <br>
    <form action="javascript:newGame();" id="newGameForm">
      <button type="submit" id="newGameButton">New Game</button>
    </form>
  </div>

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block content %}
      <!-- Main Content (Home page Content) -->
  <!-- spacer --> <br>
  <div class="w3-container w3-content w3-center w3-padding-64" style="max-width:800px" id="home">
    <h2 class="w3-wide">Joshua Agby</h2>
      <div class="w3-row">
        <img src="/static/images/profile.jpg" class="w3-circle" style="width:35%">
      </div>
    <p class="w3-opacity"><i>Mechanical and Computer Science Engineering Student</i></p>
  </div>

<style>
body {
    background-image: url("/static/images/aurum.jpg");
    background-color: #cccccc;
    background-size: cover;
    background-repeat: no-repeat;
    background-position: center center;
}
</style>


{% endblock %}

templates/resume.html
{% extends "base.html" %}
{% block content %}
      <!-- RESUME PAGE-->
  <!-- spacer --> <br>
  <div class="w3-container w3-content w3-center w3-padding-64" id="resume">
    <object height="1000" width="700" data="/static/documents/joshua_agby_resume_11_24_16.pdf" /object>
  </div>

<style>
body {
    background-image: url("/static/images/aurum.jpg");
    background-color: #cccccc;
    background-size: cover;
    background-repeat: no-repeat;
    background-position: center center;
}
</style>


{% endblock %}